# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 61adf324c45e67319d999b99dcd98aa5c4fed7fd27b24311e51f424701dfb82d4173a4c0a3ef961a8c4e91146a38fec2fd4d361f92e04b6f41e082dcb0c308f5

test:
  secret_key_base: 1aa88512984556e01b442f421a36fd16777762781cd3636622b091c247fe2dd782b047300693e9116b12a29d52764aaf32bf5e3cc41b854bcad1fb7eb59926f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
